feature: Opcode Logical And of byte with Register A into Register A
cempassi/GBMU pull request #78
Opened 2021-10-05 16:18 UTC by Gvillat

2021-10-05 23:34 UTC, cempassi requested changes

2021-10-05 23:34 UTC, cempassi commented on crates/cpu/src/opcodes/data/logical.rs
> +// const MAX_BIT3: usize = (1 << 4) - 1;
Pas de commentaire sans bonne raison

2021-10-05 23:34 UTC, cempassi commented on crates/cpu/src/opcodes/data/logical.rs
> +    let data = first & second;
Pareil que le OR, dst et src, et le sens de l'operation

2021-10-06 01:48 UTC, Gvillat commented on crates/cpu/src/opcodes/data/logical.rs
> +// const MAX_BIT3: usize = (1 << 4) - 1;
mistake were mades

2021-10-06 01:49 UTC, Gvillat commented on crates/cpu/src/opcodes/data/logical.rs
> +    let data = first & second;
ok

2021-10-06 17:10 UTC, closed without merging