feature: Opcode Logical Or of byte with Register A into Register A
cempassi/GBMU pull request #79
Opened 2021-10-05 16:40 UTC by Gvillat

2021-10-05 23:29 UTC, cempassi requested changes

2021-10-05 23:29 UTC, cempassi commented on crates/cpu/src/opcodes/data/logical.rs
> +pub fn or(first: u8, second: u8) -> u16 {
utilise source et destination quand il n'y a que deux arguments et qu'on applique l'un sur l'autre

2021-10-05 23:29 UTC, cempassi commented on crates/cpu/src/opcodes/or_reg_a.rs
> +        let data = or(data, registers.borrow().get(Bits8::A));
C'est pas A qui s'applique sur le nombre, c'est le nombre qui s'applique sur A. Les arguments sont dans le mauvais sens on dirait.
[Documentation](https://gbdev.io/pandocs/CPU_Instruction_Set.html#8-bit-arithmeticlogic-instructions)

2021-10-06 01:41 UTC, Gvillat commented on crates/cpu/src/opcodes/or_reg_a.rs
> +        let data = or(data, registers.borrow().get(Bits8::A));
N | A = A | N
mais ok

2021-10-06 01:45 UTC, Gvillat commented on crates/cpu/src/opcodes/data/logical.rs
> +pub fn or(first: u8, second: u8) -> u16 {
j'ai hesite mais ca fait plus de sens, pour moi de parler de position, plutôt que src dst vu que la source sont 2 u8 et la dest 1u8
ok :)

2021-10-06 17:10 UTC, closed without merging