feature: Opcode Increment And Decrement instructions
cempassi/GBMU pull request #82
Opened 2021-10-05 18:58 UTC by Gvillat

2021-10-05 23:43 UTC, cempassi requested changes

2021-10-05 23:43 UTC, cempassi commented on crates/cpu/src/opcodes/decrement_u8.rs
> +const MAX_BIT3: u8 = (1 << 4) - 1;
Constantes dans un fichier

2021-10-05 23:43 UTC, cempassi commented on crates/cpu/src/opcodes/decrement_u8.rs
> +            Decrement::HL => {
L'abstraction est mal faite, le code se repete, il y a un probleme

2021-10-05 23:43 UTC, cempassi commented on crates/cpu/src/opcodes/increment_u8.rs
> +            Increment::HL => {
Pareil, l'abstraction est mal faite

2021-10-06 15:17 UTC, Gvillat commented on crates/cpu/src/opcodes/decrement_u8.rs
> +            Decrement::HL => {
j'avoue !

2021-10-06 17:09 UTC, closed without merging